### PR TITLE
Add support for another vendor name

### PR DESCRIPTION
**Pull request by VincentLanglet**
The entityAuditBundle is under the simplethings vendor name, so I added support for this situation. @OskarStark

### CODE REVIEW

**Comment by OskarStark** [comment]
Good job but we will move it to our packagist orga instead

**Comment by VincentLanglet** [comment]
Can you do it @OskarStark ?

**Comment by OskarStark** [comment]
Already talking to @tolry, he will abandon it and we will resubmit it

**Comment by VincentLanglet** [comment]
Currently the release command and the dispatch one is failing because of this situation.
Shouldn't we merge this until the abandon/resubmit ? We can revert it later.

**Comment by OskarStark** [comment]
Yes feel free to merge and deploy

**Comment by VincentLanglet** [comment]
@OskarStark 
```
remote: Permission to sonata-project/EntityAuditBundle.git denied to SonataCI.                                                                                                 
  fatal: unable to access 'https://sonata-project:42716cb5f31bc7a8270511337d3c9ebaa60dd37e@github.com/sonata-project/EntityAuditBundle/': The requested URL returned error: 403
```

How I fix this ?

**Comment by OskarStark** [comment]
On what was the problem?

**Comment by VincentLanglet** [comment]
> Ok, what was the problem?

SonataCI wasn't added to the admin of the AuditEntityBundle, it's fixed now

**Pull request merged**
