### PR TITLE
Remove CacheBundle

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@core23 You approved both 
https://github.com/sonata-project/dev-kit/pull/619 and https://github.com/sonata-project/dev-kit/pull/618

Is this ok too ? :)

**Comment by core23** [comment]
Must have missed this, sorry

**Comment by VincentLanglet** [comment]
@OskarStark I dont have the rights to merge this PR. Can you do it ? :)

**Comment by VincentLanglet** [comment]
@greg0ire I dont have the rights to merge this PR. Can you do it ? :)

**Comment by greg0ire** [comment]
BTW, why is cache-bundle deprecated, but not cache?

**Comment by VincentLanglet** [comment]
@greg0ire Indeed, it is, cf https://github.com/sonata-project/cache/issues/49
Can you add [deprecated] ?

I created the PR https://github.com/sonata-project/dev-kit/pull/622

**Comment by greg0ire** [comment]
I'm starting to wonder if I should have merged this :thinking:

What's the plan regarding all the dependent packages of both the lib and the bundle? Shouldn't we move them to something else *before* deprecating those packages?

**Comment by VincentLanglet** [comment]
https://github.com/sonata-project/SonataCacheBundle/issues/279#issuecomment-599267260

**Pull request merged**
