### PR TITLE
Test on PHP 8

### PR DESCRIPTION
**Pull request by franmomu**
Testing on PHP 8
https://github.com/sonata-project/dev-kit/issues/1024

### CODE REVIEW

**Review by jordisala1991 — APPROVED** [review]

**Comment by OskarStark** [comment]
I created an issue https://github.com/symfony/symfony/issues/38246 and possible fix https://github.com/symfony/symfony/issues/38246 on symfony repo

**Comment by OskarStark** [comment]
Can you please rebase?

**Comment by OskarStark** [comment]
Why did it pass now? 🤔

**Comment by franmomu** [comment]
> Why did it pass now? 🤔

I have no idea 😕

**Comment by franmomu** [comment]
Shall we merge this @OskarStark since apparently the issue magically disappeared?

**Comment by OskarStark** [comment]
I am not sure if the tests are really executed with PHP 8 now 🧐

@jordisala1991 can you have a look here?

**Comment by jordisala1991** [comment]
It looks like yes, they are on php 8

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thanks 😊

**Pull request merged**
