### PR TITLE
Run static analysis locally

### PR DESCRIPTION
**Pull request by VincentLanglet**
I need the `memory-limit` on SonataAdmin. Don't really know why...

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Can you please rebase?

**Comment by VincentLanglet** [comment]
@OskarStark I rebased, but checks are still failing.

**Comment by OskarStark** [comment]
Yes its because its a PR from a forked repo, see: https://github.com/sonata-project/dev-kit/pull/1098

**Comment by VincentLanglet** [comment]
> Yes its because its a PR from a forked repo, see: #1098

It works on SonataAdmin, for instance: https://github.com/sonata-project/SonataAdminBundle/pull/6463.
Maybe we should use a similar check, and just return a failure instead trying to automatically fix it.

At least until the issue with fork repo is solved.

**Comment by OskarStark** [comment]
Yes we can, but in this case we can keep FlintCI

**Pull request merged**
