### PR TITLE
Add .md files to archives.

### PR DESCRIPTION
**Pull request by jlamur**
Composer archives did not have README.md, UPGRADE-*.md, ...
files.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
It should be voted before merge.

**Comment by jlamur** [comment]
If you keep the documentation, why would you not keep, at least, the CHANGELOG and UPGRADE files?

**Comment by Soullivaneuh** [comment]
For my opinion, the only reference should be on the GitHub repo with the last update.

**Comment by greg0ire** [comment]
> In my opinion, the only reference should be on the GitHub repo with the last update.

What do you mean by that?

I discussed with @rande last week and am no longer sure about this "docs exclusion" thing, that's why I didn't vote yet.

**Comment by Soullivaneuh** [comment]
> What do you mean by that?

I mean the `.md` files should not be read form the local installation but from GitHub to be sure to have the last do update.

But this is only my opinion, and my vote. :wink:

**Comment by jlamur** [comment]
Closing because we removed the docs from archives. It seems consistent to not have `*.md` files in archives too.

**Pull request closed without merging**
