### PR TITLE
Run test on php8 for media-bundle

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Review by VincentLanglet — CHANGES_REQUESTED** [review]
Should not be merged atm @OskarStark since tests are not working on media bundle for php8 https://github.com/sonata-project/SonataMediaBundle/pull/1906

**Comment by wbloszyk** [comment]
> Should not be merged atm @OskarStark since tests are not working on media bundle for php8 [sonata-project/SonataMediaBundle#1906](https://github.com/sonata-project/SonataMediaBundle/pull/1906)

In Monday I will make TODO list How to support php8 in sandbox and How to add support for Symfony 5.2 in media-bundle. I need use it in customer project.

**Review by phansys — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Need a rebase

**Comment by Yozhef** [comment]
@VincentLanglet 5 min =)

**Comment by Yozhef** [comment]
@VincentLanglet done

**Review by VincentLanglet — APPROVED** [review]

**Review by wbloszyk — APPROVED** [review]

**Comment by wbloszyk** [comment]
Thank you @Yozhef

**Comment by VincentLanglet** [comment]
Seems like there is something to improve for media-bundle https://github.com/sonata-project/SonataMediaBundle/pull/1944

We're trying to run test with 'imagine/imagine:"0.7.*"' with php8.
What about removing this test ?
The 0.x version is two year old, and we should encourage to use the stable version 1.x.

**Pull request merged**
