### PR TITLE
Fix typos in readme

### PR DESCRIPTION
**Pull request by svenluijten**

### CODE REVIEW

**Comment by svenluijten** [comment]
Hey, any indication as to when this can be merged in? 🙂

**Comment by core23** [comment]
Waiting for @Soullivaneuh . He's the merge god ;)

**Comment by svenluijten** [comment]
👍 Cool, no rush! Was just wondering.

**Comment by greg0ire** [comment]
@Soullivaneuh is quite busy ATM, I think we should help him more by compiling a list of RTM dev-kit PR every week, and prepare releases before asking for one

**Comment by core23** [comment]
Maybe use the `Projects` on GitHub in this case?

**Comment by greg0ire** [comment]
Good idea @core23

**Comment by Soullivaneuh** [comment]
Thank you @svenluijten! Will be deployed later on the sonata repositories.

**Comment by svenluijten** [comment]
👍 Sounds good!

**Pull request merged**
