### PR TITLE
Remove repeated word

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by OskarStark** [comment]
LGTM @Soullivaneuh

**Comment by Soullivaneuh** [comment]
I know @OskarStark, this is why I added the `RTM`

I wait for now to avoid tons of PR for just one typo fix.

**Comment by OskarStark** [comment]
could we do some magic here with PR labels? minor patch ?

and only execute it when we merge a minor?

**Comment by Soullivaneuh** [comment]
@OskarStark What do you mean? dev-kit is a special repository...

**Comment by OskarStark** [comment]
don't know how the process works.

i mean could we add a label to this PR which blocks job from beeing executed and create PR's on the oder repos?

**Comment by Soullivaneuh** [comment]
> i mean could we add a label to this PR which blocks job from beeing executed and create PR's on the oder repos?

The job is **really** executed by Travis only on master branch. This is why I'm not merging this one.

BTW, I think I'll change that by:

* Adding an argument to update only a specific project
* Do the global batch on a cron task at night, so Travis can process the several job without blocking all the people working on classic PR.

Trust me, Travis jobs already take hours after a dev-kit update and not all the project are configured on it. :wink:

**Comment by Soullivaneuh** [comment]
Thank you @greg0ire

**Pull request merged**
