### PR TITLE
Revert support for 3.x BlockBundle

### PR DESCRIPTION
**Pull request by wbloszyk**
This branch should be suppport as long as Sonata 4 is not finish.

### CODE REVIEW

**Comment by jordisala1991** [comment]
Careful with this one, it means dev-kit will start trying to merge 3.x into 4.x

**Comment by wbloszyk** [comment]
It is any possible to disable this auto-merging or we should upgrade dev-kit manualy for 3.x-block-bundle each time? @jordisala1991

**Comment by VincentLanglet** [comment]
> Careful with this one, it means dev-kit will start trying to merge 3.x into 4.x

If a bugfix is made on 3.x, it should be backport in 4.x too. So maybe it's the right thing to do...

**Comment by jordisala1991** [comment]
I guess so, but we are going to have an initial merge that will be huge. Not possible to disable them Atm

**Comment by wbloszyk** [comment]
> > Careful with this one, it means dev-kit will start trying to merge 3.x into 4.x
> 
> If a bugfix is made on 3.x, it should be backport in 4.x too. So maybe it's the right thing to do...

When auto-merge fail then conflict exists and should be done by manual? If yes then will be awesome becouse we have the same minimum requirements.

> I guess so, but we are going to have an initial merge that will be huge. Not possible to disable them Atm

36 files to merge, 11 to delete. It is not so huge for me. I can do it in Monday.

**Comment by greg0ire** [comment]
Let's merge this then.

**Pull request merged**
