### PR TITLE
Fix dispatch files and deprecations

### PR DESCRIPTION
**Pull request by jordisala1991**
This is the output from dev-kit: (for the doctrine-orm-admin-bundle)

```
sonata-project/doctrine-orm-admin-bundle
========================================

Files for 3.x
-------------

diff --git a/.travis.yml b/.travis.yml
index 1ccc2db..c422931 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -33,10 +33,12 @@ matrix:
     - php: '7.2'
       env: COMPOSER_FLAGS="--prefer-lowest"
     - php: '7.3'
-      env: SYMFONY=4.4.*    - php: '7.3'
+      env: SYMFONY=4.4.*
+    - php: '7.3'
       env: SYMFONY='dev-master as 4.4.x-dev'
     - php: '7.3'
-      env: SONATA_ADMIN=3.*    - php: '7.3'
+      env: SONATA_ADMIN=3.*
+    - php: '7.3'
       env: SONATA_ADMIN='dev-master as 3.x-dev'
     - php: '7.3'
       env: SYMFONY_DEPRECATIONS_HELPER=0
diff --git a/docs/conf.py b/docs/conf.py
index 8c595cd..ac8dbcc 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -48,7 +48,7 @@ source_suffix = '.rst'
 master_doc = 'index'

 # General information about the project.
-project = u''
+project = u'Sonata Doctrine Orm Admin Bundle'
 copyright = u'2010-2019, Thomas Rabaix'

 # The version info for the project you're documenting, acts as replacement for
diff --git a/tests/bootstrap.php b/tests/bootstrap.php
index 047c92d..12813b1 100644
--- a/tests/bootstrap.php
+++ b/tests/bootstrap.php
@@ -2,12 +2,6 @@

 declare(strict_types=1);

-/**
- * DO NOT EDIT THIS FILE!
- *
- * It's auto-generated by sonata-project/dev-kit package.
- */
-
 /*
  * This file is part of the Sonata Project package.
  *
@@ -17,6 +11,12 @@ declare(strict_types=1);
  * file that was distributed with this source code.
  */

+/**
+ * DO NOT EDIT THIS FILE!
+ *
+ * It's auto-generated by sonata-project/dev-kit package.
+ */
+
 /*
  * fix encoding issue while running text on different host with different locale configuration
  */
```

### CODE REVIEW

**Comment by OskarStark** [comment]
Looks good 👍🏻

@greg0ire can you deploy?

**Comment by VincentLanglet** [comment]
@jordisala1991 How did you have this output ?

When I run 
```
 bin/console dispatch
```

I get
image

**Comment by greg0ire** [comment]
I'm deploying, and I think I will run the commands manually.

**Comment by greg0ire** [comment]
Lots of FlintCI PRs are being created, here is a fix: https://github.com/sonata-project/dev-kit/pull/814

**Comment by jordisala1991** [comment]
@VincentLanglet I did it by commenting those lines:

```
                $this->updateRepositories($package, $projectConfig);
                $this->updateDevKitHook($package);
                $this->updateLabels($package);
                $this->updateBranchesProtection($package, $projectConfig);
```

For me we should separate the dispatch config repository from dispatch files. And then you could execute it locally.
Then we could do what @OskarStark suggested on a issue: having automatically reports on pull request with comment from dev-kit. (that could be done using some github actions like: https://github.com/marketplace/actions/create-or-update-comment)

And, we could move all that is on symfony cloud to github actions too, that would allow not to depend on someone making a deploy. On Github actions we could configure all the crons and the secrets to execute those crons.

**Comment by greg0ire** [comment]
> And, we could move all that is on symfony cloud to github actions too, that would allow not to depend on someone making a deploy

Yes please :sob:

**Comment by jordisala1991** [comment]
Symfony cloud could be used to deploy the sandbox (not sure what agreement we have with symfony to let us use the cloud).

**Comment by jordisala1991** [comment]
The ony thing that can't be done with github actions or we have to rethink a bit is the webhooks configured. But that is not something that need frequent redeploy. Maybe we can maintain symfony cloud for now , but without crons that can be configured on github actions.

**Comment by VincentLanglet** [comment]
I can work on the split of the dispatch command.

Do you want to work on the automation @jordisala1991 ?

**Comment by jordisala1991** [comment]
I can do that on september, for now I would like to keep focusing on SonataAdminBundle Narrow API

**Comment by VincentLanglet** [comment]
> I can do that on september, for now I would like to keep focusing on SonataAdminBundle Narrow API

Sure I create an issue https://github.com/sonata-project/dev-kit/issues/820
I also create mine https://github.com/sonata-project/dev-kit/issues/819

**Comment by OskarStark** [comment]
BTW you guys can also get access on the Symfony cloud instance.

Just send me your email of your Symfony connect account

**Comment by VincentLanglet** [comment]
> Just send me your email of your Symfony connect account

Done on slack

**Pull request merged**
