### PR TITLE
[WIP] Symfony way

### PR DESCRIPTION
**Pull request by soullivaneuh**
The goal is to take profit of Symfony services container and controllers.

I'll try to not introduce the full stack as we don't need it for this project.

cc @greg0ire 
- [ ] Use Symfony services on commands
- [ ] Introduce Symfony controllers
- [ ] Remove Silex
- [ ] Rework parameters and config (.env not needed) if necessary
- [ ] Add some unit and feature tests (behat)

### CODE REVIEW

**Comment by greg0ire** [comment]
"Freature" makes me hungry :trollface:

**Comment by greg0ire** [comment]
How about a container interop implementation instead? Won't sf move to this one day?

**Comment by Soullivaneuh** [comment]
> How about a container interop implementation instead? Won't sf move to this one day?

You got my attention, can you develop?

**Comment by greg0ire** [comment]
I'm in the train right now so hard to develop but IIRC there is a PSR for containers, so let's use an implementation of this standard maybe?

**Comment by Soullivaneuh** [comment]
You mean this one? https://github.com/php-fig/fig-standards/blob/master/proposed/container.md

Right, if you say Symfony will go for it, we can use it waiting that, no? Or have you other suggestions?

**Comment by greg0ire** [comment]
Looks like it is not even accepted yet and symfony container already named its method the right way so let's use sf

**Comment by core23** [comment]
Are you still working on this @Soullivaneuh ?

**Comment by core23** [comment]
This PR looks dead. Feel free to reopen if you will continue working on this.

**Pull request closed without merging**
