### PR TITLE
Fail on warning in PHPUnit

### PR DESCRIPTION
**Pull request by franmomu**
This way we can detect possible problems easily

For example in MediaBundle tests pass: https://github.com/sonata-project/SonataMediaBundle/runs/1107304396
And adding the configuration: https://github.com/sonata-project/SonataMediaBundle/pull/1809/checks?check_run_id=1124107416

Other refs: https://github.com/sonata-project/SonataClassificationBundle/pull/581, https://github.com/sonata-project/SonataMediaBundle/pull/1807, https://github.com/sonata-project/SonataAdminBundle/pull/6381#discussion_r485527010

### CODE REVIEW

**Review by jordisala1991 — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
@franmomu can you please check the open DevKit PR's ? A lot of them are failing now

**Comment by OskarStark** [comment]
https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3ASonataCI+archived%3Afalse+

**Comment by franmomu** [comment]
I'll take a look!

**Comment by franmomu** [comment]
I've fixed a couple of them, I have to go, I keep going later.

**Pull request merged**
