### PR TITLE
Removed unstable branch for dashboard-bundle

### PR DESCRIPTION
**Pull request by core23**
As long as we don't have a stable release, we could use the master branch for development. 

We are <1.0, so we can't have any BC break, which would justify a separate branch.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
That change not really nothing. 1.x is the default branch, so let's work on this only and the backport will be automatically made on master.

BTW, doing this would produce weird results on documentation.

**Comment by Soullivaneuh** [comment]
@core23 Can I close it or do you have anything to say about my comment?

**Comment by core23** [comment]
I don't get the advantage of supporting a `0.x` / dev branch and a `master` branch for the moment. We should remove the `0.x` branch unless we have a stable 1.x release.

**Comment by Soullivaneuh** [comment]
I get that at your first comment. What about my answer?

Sullivan SENECHAL
Le 15 juin 2016 19:24, "Christian Gripp" <notifications@github.com> a
écrit :

**Comment by Soullivaneuh** [comment]
After reflection, this is the same case for admin-search-bundle.

I can do that, but all opened PR will be automatically closed.

Do you confirm @core23 ?

**Comment by core23** [comment]
Maybe we should remove the branch on the admin search bundle first, because there are no open PRs.

For the dashboard bundle: Could we remove the master and rename the 0.x branch to master to port all PRs? Never tried :/

**Comment by core23** [comment]
Or just wait until we accept all open PRs? What do you think @greg0ire

**Comment by Soullivaneuh** [comment]
> Maybe we should remove the branch on the admin search bundle first, because there are no open PRs.

You didn't understand me, there is no 0.x branch on admin-search: https://github.com/sonata-project/SonataAdminSearchBundle/branches

Nothing to do here.

> For the dashboard bundle: Could we remove the master and rename the 0.x branch to master to port all PRs? Never tried :/

I don't think we can do that. "Renaming a branch" is the same as push a new one and delete the all.

@greg0ire Can you confirm?

**Comment by greg0ire** [comment]
> I don't think we can do that. "Renaming a branch" is the same as push a new one and delete the all.

I think so too.

**Pull request merged**
