### PR TITLE
Join the Hacktoberfest

### PR DESCRIPTION
**Pull request by core23**
**Support and celebrate open source. Earn a limited edition T-shirt.**
https://github.com/blog/2260-hacktoberfest-is-back

We could join this event and to support the open source community and get some more contributions.

### CODE REVIEW

**Comment by core23** [comment]
Ping @sonata-project/contributors

**Comment by Soullivaneuh** [comment]
> Once you've made your contribution, tell the world about it with the #hacktoberfest hashtag on Twitter, Facebook, or Instagram. :tada:

I don't see why we have to add this tag on the issue tracker.

**Comment by core23** [comment]
You have to solve at lest 4(?) issues with a `hacktoberfest` label to get these awesome shirts.

**Comment by Soullivaneuh** [comment]
Yeah but the labels is for social network apparently. Or am I wrong?

**Comment by core23** [comment]
They are needed for GitHub to find the users who contributed 4 times+

You could use twitter, facebook, ... to spread the message. But this isn't needed

**Comment by OskarStark** [comment]
I think we should join, if the only thing is to create a label and apply them to a few tickets!

At least we would get some cool T-Shirts 💃

**Comment by greg0ire** [comment]
Before October ends if possible :troll:

**Comment by Soullivaneuh** [comment]
I didn't see where this label is need but ok, I trust you. :wink:

**Pull request merged**
