### PR TITLE
Join the Hacktoberfest (again)

### PR DESCRIPTION
**Pull request by core23**
Support and celebrate open source. Earn a limited edition T-shirt.
https://github.com/blog/2433-celebrate-open-source-this-october-with-hacktoberfest

We could join this event again (#210) to support the open source community and get some more contributions.

### CODE REVIEW

**Comment by jlamur** [comment]
> If you receive “spammy” pull requests, please let us know by applying the “invalid” label.

Should we also the "invalid" label?

**Comment by core23** [comment]
> Should we also add the "invalid" label?

Nothing to do with the hacktoberfest. If is in invalid issue / PR we should close it.

**Comment by jlamur** [comment]
> Nothing to do with the hacktoberfest. If is in invalid issue / PR we should close it.

Are you sure? Their website explicitly says to add a label "invalid" when a PR is spammy.
I think they count closed PR.

**Comment by core23** [comment]
You're right, but I'm not sure if we need this, just for the hacktoberfest. We decide which PR is marked as `hacktoberfest` and which get merged.

**Comment by jordisala1991** [comment]
IMO if we face spam problems, then we can create that other label

**Pull request merged**
