### PR TITLE
 Do not set patch version for PHPUnit for dev-kit

### PR DESCRIPTION
**Pull request by wbloszyk**

### CODE REVIEW

**Comment by jordisala1991** [comment]
This is already solved

**Comment by jordisala1991** [comment]
Keep in mind to not open branches on upstream (unless you really need it)

**Comment by wbloszyk** [comment]
@jordisala1991 

> This is already solved

Do we have dev-kit project in dev-kit projects? :smile: This is not solve for dev-kit phpunit. 
https://github.com/sonata-project/dev-kit/blob/18849143e2215db7919485e19c8fba8d8571e53e/phpunit.xml.dist#L28

**Comment by jordisala1991** [comment]
Oh! I didn't saw you changed the other phpunit.xml.dist. Sorry!, can you recreate the PR?

**Pull request closed without merging**
