### PR TITLE
Add drivers folder to gitignore if panther is used

### PR DESCRIPTION
**Pull request by VincentLanglet**
Since the version `0.9` of panther 
```
composer require --dev dbrekelmans/bdi
vendor/bin/bdi detect drivers
```
is required

We need to ignore the folder `drivers` then.

Any idea how to run `vendor/bin/bdi detect drivers` automatically too ?

### CODE REVIEW

**Comment by franmomu** [comment]
I created https://github.com/sonata-project/dev-kit/pull/1360, but as it looked like it worked without it, I closed it.

**Comment by VincentLanglet** [comment]
@franmomu I get the error locally, so I think it's still needed.

And it shouldn't be added to the CI but directly to the composer.json or the developer can't test locally.

**Comment by franmomu** [comment]
yeah, but you can add the `name: Download WebDriver drivers` part to CI.

**Comment by VincentLanglet** [comment]
> yeah, but you can add the `name: Download WebDriver drivers` part to CI.

If we don't find a better solution, it could be inside the `make test` command or we could add a `make pretest`.
We have multiple solutions for the CI.

I was more concern for the first time contributor who try to run test and get an error with `vendor/bin/simple-phpunit tests`.
That's why I was wondering if we could run something in the custom_bootstrap.php or something similar.

**Comment by OskarStark** [comment]
Any news here? Shall we merge this?

**Comment by VincentLanglet** [comment]
> Any news here? Shall we merge this?

IMHO we should

**Review by OskarStark — APPROVED** [review]

**Pull request merged**
