### PR TITLE
Unify github action styles, remove paths from test trigger

### PR DESCRIPTION
**Pull request by jordisala1991**
There are more than one thing in this PR:

* I have unified styles for the github actions workflow files.
* I have removed conditions for PRs on the test workflow. Why? because if we mark those builds as required, they will be required on each build. Now the tests run faster than ever and that should not be a problem.
* I have modified lint and documentation actions to only run for push on desired branches, no more dev-kit PRs with double builds

Diff for classification-bundle:

```diff
diff --git a/.github/workflows/documentation.yaml b/.github/workflows/documentation.yaml
index 0cbb4b2..f7cd7bd 100644
--- a/.github/workflows/documentation.yaml
+++ b/.github/workflows/documentation.yaml
@@ -2,64 +2,65 @@
 #
 # It's auto-generated by sonata-project/dev-kit package.

+name: Documentation
+
 on:
-    push:
-        paths:
-            - 'docs/**'
+  push:
+    branches:
+      - master
+      - 3.x

-    pull_request:
-        paths:
-            - 'docs/**'
-
-name: Documentation
+  pull_request:
+    paths:
+      - 'docs/**'

 jobs:
-    build:
-        name: Build
+  build:
+    name: Build
+
+    runs-on: ubuntu-latest

-        runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2

-        steps:
-            - name: "Checkout"
-              uses: actions/checkout@v2
+      - name: Set up Python 3.7
+        uses: actions/setup-python@v1
+        with:
+          python-version: '3.7'

-            - name: "Set up Python 3.7"
-              uses: actions/setup-python@v1
-              with:
-                  python-version: '3.7' # Semantic version range syntax or exact version of a Python version
+      - name: Display Python version
+        run: python -c "import sys; print(sys.version)"

-            - name: "Display Python version"
-              run: python -c "import sys; print(sys.version)"
+      - name: Install Sphinx dependencies
+        run: sudo apt-get install python-dev build-essential

-            - name: "Install Sphinx dependencies"
-              run: sudo apt-get install python-dev build-essential
+      - name: Cache pip
+        uses: actions/cache@v2
+        with:
+          path: ~/.cache/pip

-            - name: "Cache pip"
-              uses: actions/cache@v2
-              with:
-                  path: ~/.cache/pip
-                  key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
-                  restore-keys: |
-                      ${{ runner.os }}-pip-
+          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
+          restore-keys: ${{ runner.os }}-pip-

-            - name: "Install custom requirements via pip"
-              run: pip install -r docs/requirements.txt
+      - name: Install custom requirements via pip
+        run: pip install -r docs/requirements.txt

-            - name: "Build documentation"
-              run: make docs
+      - name: Build documentation
+        run: make docs

-    doctor-rst:
-        name: DOCtor-RST
+  doctor-rst:
+    name: DOCtor-RST

-        runs-on: ubuntu-latest
+    runs-on: ubuntu-latest

-        steps:
-            - name: "Checkout"
-              uses: actions/checkout@v2
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2

-            - name: "Run DOCtor-RST"
-              uses: docker://oskarstark/doctor-rst
-              with:
-                  args: --short
-              env:
-                  DOCS_DIR: 'docs/'
+      - name: Run DOCtor-RST
+        uses: docker://oskarstark/doctor-rst
+        with:
+          args: --short
+        env:
+          DOCS_DIR: 'docs/'
diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
index 9065a71..15ee1c8 100644
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -2,68 +2,76 @@
 #
 # It's auto-generated by sonata-project/dev-kit package.

-on: [push, pull_request]
-
 name: Lint

+on:
+  push:
+    branches:
+      - master
+      - 3.x
+
+  pull_request:
+
 jobs:
-    php-cs-fixer:
-        name: PHP-CS-Fixer
+  php-cs-fixer:
+    name: PHP-CS-Fixer

-        runs-on: ubuntu-latest
+    runs-on: ubuntu-latest

-        steps:
-            - name: "Checkout"
-              uses: actions/checkout@v2
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2

-            - name: "Run PHP-CS-Fixer"
-              uses: docker://oskarstark/php-cs-fixer-ga:2.16.4
-              with:
-                  args: --ansi --verbose --diff --dry-run
+      - name: Run PHP-CS-Fixer
+        uses: docker://oskarstark/php-cs-fixer-ga:2.16.4
+        with:
+          args: --ansi --verbose --diff --dry-run

-    composer-normalize:
-        name: composer-normalize
+  composer-normalize:
+    name: composer-normalize

-        runs-on: ubuntu-latest
+    runs-on: ubuntu-latest

-        steps:
-            - name: "Checkout"
-              uses: actions/checkout@v2
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2

-            - name: "Run composer-normalize"
-              uses: docker://ergebnis/composer-normalize-action:0.8.0
-              with:
-                  args: --dry-run
+      - name: Run composer-normalize
+        uses: docker://ergebnis/composer-normalize-action:0.8.0
+        with:
+          args: --dry-run

-    yaml-files:
-        name: YAML files
+  yaml-files:
+    name: YAML files

-        runs-on: ubuntu-latest
+    runs-on: ubuntu-latest

-        steps:
-            - name: "Checkout"
-              uses: actions/checkout@v2
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2

-            - name: "Install Ruby 2.6"
-              uses: actions/setup-ruby@v1
-              with:
-                  ruby-version: '2.6'
+      - name: Install Ruby 2.6
+        uses: actions/setup-ruby@v1
+        with:
+          ruby-version: '2.6'

-            - run: gem install yaml-lint
+      - name:
+        run: gem install yaml-lint

-            - name: "Linting..."
-              run: make lint-yaml
+      - name: Lint files
+        run: make lint-yaml

-    xml-files:
-        name: XML files
+  xml-files:
+    name: XML files

-        runs-on: ubuntu-latest
+    runs-on: ubuntu-latest

-        steps:
-            - name: "Checkout"
-              uses: actions/checkout@v2
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2

-            - run: sudo apt-get update && sudo apt-get install libxml2-utils
+      - name: Install required dependencies
+        run: sudo apt-get update && sudo apt-get install libxml2-utils

-            - name: "Linting..."
-              run: make lint-xml
+      - name: Linting...
+        run: make lint-xml
diff --git a/.github/workflows/stale.yaml b/.github/workflows/stale.yaml
index 9679ec4..265e876 100644
--- a/.github/workflows/stale.yaml
+++ b/.github/workflows/stale.yaml
@@ -4,7 +4,7 @@

 # https://github.com/actions/stale

-name: "Stale"
+name: Stale

 on:
   schedule:
@@ -12,24 +12,24 @@ on:

 jobs:
   stale:
-    runs-on: "ubuntu-latest"
+    runs-on: ubuntu-latest

     steps:
-      - name: "Close stale issues and pull requests"
+      - name: Close stale issues and pull requests

-        uses: "actions/stale@v1.1.0"
+        uses: actions/stale@v1.1.0

         with:
           days-before-close: 7
           days-before-stale: 180
-          repo-token: "${{ secrets.GITHUB_TOKEN }}"
-          exempt-issue-label: "keep"
-          stale-issue-label: "stale"
+          repo-token: ${{ secrets.GITHUB_TOKEN }}
+          exempt-issue-label: keep
+          stale-issue-label: stale
           stale-issue-message: >
             This issue has been automatically marked as stale because it has not had
             recent activity. It will be closed if no further activity occurs. Thank you
             for your contributions.
-          stale-pr-label: "stale"
+          stale-pr-label: stale
           stale-pr-message: >
             This PR has been automatically marked as stale because it has not had
             recent activity. It will be closed if no further activity occurs. Thank you
diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
index fd6928f..bbe97e4 100644
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -11,7 +11,6 @@ on:
       - 3.x

   pull_request:
-    paths: ['**.php', '**.yml', '**.yaml', '**.xml', '**.xml.dist', '**.twig', '**.js', '**.css', '**.json']

 jobs:
   test:
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
This avoid having to do this other PR: #844 @OskarStark

**Comment by jordisala1991** [comment]
Proof PR: https://github.com/sonata-project/SonataClassificationBundle/pull/563

**Review by OskarStark — CHANGES_REQUESTED** [review]
Can you please adjust the workflow files of `dev-kit` accordingly? Thanks!

**Comment by jordisala1991** [comment]
Done

**Review by OskarStark — APPROVED** [review]

**Pull request merged**
