### PR TITLE
Fix injection of git wrapper

### PR DESCRIPTION
**Pull request by VincentLanglet**
Fix
https://github.com/sonata-project/dev-kit/pull/799#issuecomment-668169593

### CODE REVIEW

**Comment by core23** [comment]
Can't you add a new `GitWrapper` service, so we could use autowiring?

**Comment by VincentLanglet** [comment]
Like this @core23 ?

**Comment by OskarStark** [comment]
Can you please deploy @greg0ire

**Comment by OskarStark** [comment]
I deployed!

**Comment by OskarStark** [comment]
Hmm...

Screenshot 2020-08-04 18 16 04

**Comment by VincentLanglet** [comment]
Before it was 
```
$this->twig = new Environment(new FilesystemLoader(__DIR__.'/../..'));
```

now, with the injection, seems like it's only looking inside `/templates`.

What would be the best solution @sonata-project/contributors ?
- moving `project` folder inside the `template` folder
- changing `$this->twig->render($localPath, ...)` to `$this->twig->render('../'.$localPath, ...)` 
- something else ?

I think the first solution is not a bad one, after all, all the file inside the `project` dir are what we can call templates.

**Comment by jordisala1991** [comment]
https://symfony.com/doc/current/reference/configuration/twig.html#paths

Configure another twig path

**Comment by VincentLanglet** [comment]
> https://symfony.com/doc/current/reference/configuration/twig.html#paths
> 
> Configure another twig path

`project` dir is in the root dir. I'm not sure that adding the root dir of the project as a twig path is nice.

Plus, the signature of the method use to render a file is
```
private function renderFile(Package $package, $repositoryName, $localPath, $distPath, array $projectConfig, $branchName): void
```

Currently we're calling this with `$localPath = 'project'`.
Is does not seems stupid to me to require that `$localPath` should refer to a path inside the `templates` dir. (Or it can be inside another dir if you prefer and we add it as a twig path, but IMO it shouldn't be directly in the rootDir).

**Comment by VincentLanglet** [comment]
> > https://symfony.com/doc/current/reference/configuration/twig.html#paths
> > Configure another twig path
> 
> `project` dir is in the root dir. I'm not sure that adding the root dir of the project as a twig path is nice.
> 
> Plus, the signature of the method use to render a file is
> 
> ```
> private function renderFile(Package $package, $repositoryName, $localPath, $distPath, array $projectConfig, $branchName): void
> ```
> 
> Currently we're calling this with `$localPath = 'project'`.
> Is does not seems stupid to me to require that `$localPath` should refer to a path inside the `templates` dir. (Or it can be inside another dir if you prefer and we add it as a twig path, but IMO it shouldn't be directly in the rootDir).

Hi @sonata-project/contributors. I'll want to make the PR to fix this.
But I would prefer to have your opinion about what is the best solution.

**Comment by OskarStark** [comment]
Would move the folder in templates folder 👍🏻

**Pull request merged**
