### PR TITLE
Use phpunit from installed vendors

### PR DESCRIPTION
**Pull request by jordisala1991**
Proof: https://github.com/sonata-project/SonataAdminBundle/pull/7540

### CODE REVIEW

**Comment by jordisala1991** [comment]
For me I would do it only for phpunit for the moment (we also have composer-normalizer usage and we do not install on composer.json)

But @VincentLanglet requested it for both tools. I can't make both of you happy it seems. What should I do?

**Comment by core23** [comment]
> But @VincentLanglet requested it for both tools. I can't make both of you happy it seems. What should I do?

Install phpunit as a dev dependency and all other tools via separate composer config?

**Comment by jordisala1991** [comment]
With this PR we have a few good things solved:

* PHPUnit installed on each project (as Symfony recommends and it solves the build problem)
* php-cs-fixer updated to last v3 automatically (before it depended on the @OskarStark action)
* composer normalizer updated to use the same strategy as php-cs-fixer (also the action is kind of deprecated)

Whats missing?

* A specific composer.json for tools (IMO it can be done later if we need to)
* The ability to run php-cs-fixer and composer-normalize on each contributor computer (that needs a specific composer.json for tools or add them to our composer.json which @core23 do not agree)

The missing points can be solved later IMHO

**Comment by VincentLanglet** [comment]
> But @VincentLanglet requested it for both tools. I can't make both of you happy it seems. What should I do?

I won't make phpcsfixer as a blocking point if @core23 is not happy with it.

My issue is that I am not able to run phpcsfixer on sonata projects because it require it globally and I cannot change the version I have globally.

But it could be great to find a solution later to
> The ability to run php-cs-fixer and composer-normalize on each contributor computer (that needs a specific composer.json for tools or add them to our composer.json which @core23 do not agree)

Still, thanks for the work @jordisala1991 :)

**Pull request merged**
