### PR TITLE
remove travis lint TARGET

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by OskarStark** [comment]
Another thing we need todo, when merging this: flintci integration needs to be required!

**Comment by greg0ire** [comment]
> Another thing we need todo, when merging this: flintci integration needs to be required!

And by when, you mean "just before", right?

**Comment by Soullivaneuh** [comment]
I prefer to keep it in case we have another linters we can run only on Travis.

**Comment by OskarStark** [comment]
Ok, lets close it for now

**Comment by OskarStark** [comment]
Closing in favor of https://github.com/sonata-project/dev-kit/pull/461

**Pull request closed without merging**
