### PR TITLE
Bump PHP versions tests to 5.6

### LINKED ISSUE #52: Next major: PHP version support
Let's talk about PHP version support drop for next major of sonata bundles.

Ref: http://php.net/supported-versions.php

PHP 5.5 will be not supported at all by the company soon (2 months).

PHP 5.6 is still supported for more than 2 years and I think we have to keep at least one PHP 5 support for the moment.

SF 3.0 supports PHP 5.5+ but I don't think we should absolutely follow them, we have not the same dynamic.

Let's do a vote for this too (emoji reaction):

:+1: for PHP 5.6+ support
:-1: for PHP 5.5+ support

Feel free to elaborate your thinking on this issue. :+1: 

cc @sonata-project/contributors

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Closes #52.

This will update Travis config **only**. Modifications have to be made on the `composer.json` of each project too.

@sonata-project/contributors If you have any suggestion/question, feel free! :+1:

### CODE REVIEW

**Comment by core23** [comment]
Can we apply this rule, because https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1985 was merged?

**Comment by Soullivaneuh** [comment]
I would like to setup this. But I won't have enough time to do this:

> Modifications have to be made on the composer.json of each project too.

@sonata-project/contributors anyone to open an issue listing project having to be updated and start the migration?

**Comment by Soullivaneuh** [comment]
Note: Have to add the rule on `.styleci.yml` before merging this one.

**Comment by core23** [comment]
> anyone to open an issue listing project having to be updated and start the migration?

Created an issue for this @Soullivaneuh  #208 

> Note: Have to add the rule on .styleci.yml before merging this one.

Please have a look at https://github.com/sonata-project/dev-kit/pull/209

**Pull request merged**
