### PR TITLE
Remove 3.x from block-bundle

### PR DESCRIPTION
**Pull request by jordisala1991**

### CODE REVIEW

**Comment by jordisala1991** [comment]
It would be nice to have a way to create a release for an unmaintained branch. Like: this branch wont receive more dev kit updates but can receive fixes an we can create a release for it if needed.

**Comment by VincentLanglet** [comment]
> It would be nice to have a way to create a release for an unmaintained branch. Like: this branch wont receive more dev kit updates but can receive fixes an we can create a release for it if needed.

Since the https://d5zda2diva-x6miu6vkqhzpi.eu.s5y.io/next-releases page cannot display all the release, it's maybe better to change the strategy by displaying a link for all the project stable branch.
This avoid to remember the project name used in the url, like
https://d5zda2diva-x6miu6vkqhzpi.eu.s5y.io/next-release/admin-bundle/4.x

Then it will be easy to change 4.x to 3.x if needed for instance.

**Comment by VincentLanglet** [comment]
Also, we could drop 7.3 on most of the branches now https://www.php.net/supported-versions.php

**Comment by jordisala1991** [comment]
> Also, we could drop 7.3 on most of the branches now https://www.php.net/supported-versions.php

Yes, we already drop from some projects.

**Review by VincentLanglet — APPROVED** [review]

**Review by core23 — APPROVED** [review]

**Pull request merged**
