### PR TITLE
Test - automatic CS fix + commit (in a PR from forked repo)

### PR DESCRIPTION
**Pull request by OskarStark**
Lets see if a PR receives an automatic CS fix

### CODE REVIEW

**Comment by OskarStark** [comment]
@localheinz any idea why this works with a branch of the same repo in https://github.com/sonata-project/dev-kit/pull/1097, but not a remote branch? 🤔

**Comment by jordisala1991** [comment]
You should add pull_request_target to the action trigger

**Comment by OskarStark** [comment]
I tried, as you can see in the latest checks down below... 🤔 

CleanShot 2020-09-24 at 07 18 03

Maybe @stefanzweifel can help us 😄

**Comment by stefanzweifel** [comment]
👋

The  php-cs-fixer runs fail, as the "Test/ PHP 8.0" run fails first: https://github.com/sonata-project/dev-kit/runs/1154581328#step:10:4
The php-cs-fixer runs never actually make it to the "fix and commit" part of the workflow.

**Comment by OskarStark** [comment]
Hey, thanks for reaching out 👋 

>The php-cs-fixer runs fail, as the "Test/ PHP 8.0" run fails first:

In this PR https://github.com/sonata-project/dev-kit/pull/1097 PHP 8-0 was failing too 🤔

**Comment by OskarStark** [comment]
AFAIK @localheinz is working on https://github.com/ergebnis/playground/pull/230, too, but in this case he is fixing a local branch instead of a pull request branch from the outside repository 🤔

**Comment by OskarStark** [comment]
@stefanzweifel, no the PHP 8.0 build is green, but the others are still failing :(

**Comment by stefanzweifel** [comment]
It seems GitHub can't clone this repo anymore: https://github.com/sonata-project/dev-kit/pull/1098/checks?check_run_id=1186863006#step:3:38

There's [an open issue](https://github.com/actions/checkout/issues/143) on the `actions/checkouts`-repo which seems related to this; but without fix. 
Maybe by setting some more env variables you can see more about the error: https://github.com/actions/checkout/issues/143#issuecomment-613103338

**Comment by OskarStark** [comment]
@stefanzweifel I added:
```
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
```

**Comment by stefanzweifel** [comment]
@OskarStark Thanks! I still have no good evidence why the checkout in the linter runs fails.

I think it could be related that the run is triggered from a forked repository. 🤔 
For both the `pull_request` and `pull_request_target`-triggers, GitHub tries to checkout the `sonata-project/dev-kit` with the ref `OskarStark-patch-1`

- https://github.com/sonata-project/dev-kit/pull/1098/checks?check_run_id=1286256461#step:3:3
- https://github.com/sonata-project/dev-kit/pull/1098/checks?check_run_id=1286256649#step:3:3

In `git-auto-commit` we had a similar problem recently (https://github.com/stefanzweifel/git-auto-commit-action/issues/117#issuecomment-710822378). 
My guess is, that GitHub changed something on their side around how forks work with GitHub Actions - or didn't update (or improved) the docs yet. 

Maybe you could give it a go by removing the `with/ref`-part in the workflow?
The other steps in your workflow can checkout the code just fine. 🤔

**Comment by OskarStark** [comment]
Thanks for the feedback 🙏 

> Maybe you could give it a go by removing the with/ref-part in the workflow?

Sure, I did, lets see...

**Comment by OskarStark** [comment]
Nothing... 😞

**Comment by stefanzweifel** [comment]
Interesting.
`pull_request` fails as it tries to push the branch from your forked repo to the base repo. Fails as the branch `OskarStark-patch-1` doesn't exist on `https://github.com/sonata-project/dev-kit`.
https://github.com/sonata-project/dev-kit/pull/1098/checks?check_run_id=1288423771#step:5:14

`pull_request_target` fails, as it tries to checkout the branch from the fork in the base repo. Also fails as the branch `OskarStark-patch-1` doesn't exist on `https://github.com/sonata-project/dev-kit`.
https://github.com/sonata-project/dev-kit/pull/1098/checks?check_run_id=1288423570#step:3:4


I've just tagged a new version of git-auto-commit with adds a `checkout_options`-option. You could theoretically use it with `'checkout_options: -b'` to force the action to create a new branch and push that branch to the remote. But this will probably also not work here as it's a fork.

The README of git-auto-commit has recently been updated to point these issues with forks out. Actions like this which run a linter/fixer should probably run on a `push`-trigger on the `main`-branch of the repo. Makes life thousand times easier. 😅 
https://github.com/stefanzweifel/git-auto-commit-action#using-the-action-in-forks-from-public-repositories

(But I understand that it would be great if it would work in a PR)

**Comment by OskarStark** [comment]
> You could theoretically use it with 'checkout_options: -b' to force the action to create a new branch and push that branch to the remote.

I try, thanks 👍 

> Actions like this which run a linter/fixer should probably run on a push-trigger on the main-branch of the repo. Makes life thousand times easier.

Well I agree here, but it makes diffs harder to read, creates comments by people who doesn't know this + if you revert something ... its not so clean IMHO.

**Pull request closed without merging**
