### PR TITLE
Add php7.2

### PR DESCRIPTION
**Pull request by jordisala1991**
PHP 7.2 is out

### CODE REVIEW

**Comment by greg0ire** [comment]
Could you make a proof PR? I gave up trying to make it work on greg0ire/enum yesterday, there were many issues...

**Comment by Soullivaneuh** [comment]
> there were many issues...

Like what?

**Comment by greg0ire** [comment]
Like the Travis box still using the beta version, and an `eval()` call I couldn't find in my code.

**Comment by greg0ire** [comment]
See https://travis-ci.org/greg0ire/enum/jobs/309749310#L629

**Comment by jordisala1991** [comment]
There are some bundles that produce errors on 7.2, here are the PR that need to be merged:

https://github.com/sonata-project/SonataDatagridBundle/pull/110
https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/511
https://github.com/sonata-project/SonataClassificationBundle/pull/355
https://github.com/sonata-project/SonataAdminBundle/pull/4818

**Comment by OskarStark** [comment]
I added a todo list. All checked ones are merged

**Comment by Soullivaneuh** [comment]
Can't we merge this PR and fix code on dev-kit ones?

**Comment by jordisala1991** [comment]
Everything is fixed. PHPCR is failing because of a lot of other things... to discuss on another issue or on slack

**Comment by Soullivaneuh** [comment]
So let's go then.

**Pull request merged**
