### PR TITLE
[RFC] Allow core members to be advertised for sponsoring

### PR DESCRIPTION
**Pull request by OskarStark**
I checked all core members, but only @core23 and me are registered for GithubSponsors.

Are some of you using another platform such as:
CleanShot 2020-09-24 at 08 45 08

WDYT?

### CODE REVIEW

**Comment by VincentLanglet** [comment]
I thought I registered myself to GithubSponsors

**Comment by OskarStark** [comment]
> I thought I registered myself to GithubSponsors

Oh I didn't see it, right, I added you!

**Comment by VincentLanglet** [comment]
By the way, does sponsoring work for a team.

I mean, if possible, we should allow to sponsor "Sonata-team" in order to pay server/symfony-cloud or things like this.

**Comment by OskarStark** [comment]
> By the way, does sponsoring work for a team.

I don't know

**Pull request merged**
