### PR TITLE
Run test on php8 for classification-bundle

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Comment by Yozhef** [comment]
blocked by https://github.com/sonata-project/SonataClassificationBundle/pull/653

**Comment by jordisala1991** [comment]
Can you solve conflicts here @Yozhef ?

**Comment by Yozhef** [comment]
@jordisala1991 tomorrow it's okay?

**Comment by jordisala1991** [comment]
Yes! Thank you :)

**Comment by Yozhef** [comment]
@jordisala1991 sorry that so long covid changed my plans = (

**Comment by jordisala1991** [comment]
Dont worry. @sonata-project/contributors can we merge those 2?

**Pull request merged**
