### PR TITLE
Fix cyclic dependency on QA

### PR DESCRIPTION
**Pull request by jordisala1991**

### CODE REVIEW

**Comment by jordisala1991** [comment]
Proof PR: https://github.com/sonata-project/SonataBlockBundle/pull/767

... It does not work for phpstan, but it does for psalm..

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
> ... It does not work for phpstan, but it does for psalm..

Hmm, if it does not work for PHPStan, shall we just add it for Psalm now?

**Comment by jordisala1991** [comment]
Yes, but it won't fully solve the issue.

**Comment by jordisala1991** [comment]
Fixed only the psalm now.

**Pull request merged**
