### PR TITLE
Remove extra empty lines and add lint rule

### PR DESCRIPTION
**Pull request by VincentLanglet**
I'm trying to create a failure first: https://github.com/sonata-project/SonataAdminBundle/pull/6925

### CODE REVIEW

**Review by phansys — APPROVED** [review]

**Review by wbloszyk — APPROVED** [review]

**Comment by phansys** [comment]
The rule seems to be not detecting that extra empty LF.

**Comment by phansys** [comment]
"would" !== "will" :smile: 
>the following code snippet would FAIL

Maybe `yamllint` is not introspecting directories that start with a dot, like `.github/`.

**Comment by VincentLanglet** [comment]
Seems like we're not using `yamllint` https://yamllint.readthedocs.io/en/stable/quickstart.html#installing-yamllint
but `yaml-lint` https://github.com/sonata-project/dev-kit/blob/master/.github/workflows/lint.yaml#L53

**Review by phansys — APPROVED** [review]

**Review by wbloszyk — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Test are green, I updated the config to:
```
rules:
    comments: disable
    comments-indentation: disable
    document-start: disable
    empty-lines:
        max: 1
        max-start: 0
        max-end: 0
    line-length: disable
    truthy:
        allowed-values: ['true', 'false']
        check-keys: false
```

**Review by phansys — APPROVED** [review]

**Comment by phansys** [comment]
`/request-deploy`

**Comment by VincentLanglet** [comment]
> `/request-deploy`

Done ; I remembered how ^^'

**Pull request merged**
