### PR TITLE
removed obsolete labels

### PR DESCRIPTION
**Pull request by OskarStark**
removed "review required" and "RTM" label, as github now provides a better workflow to handle PR's

### CODE REVIEW

**Comment by OskarStark** [comment]
Maybe keep the `RTM` only for dashboard as @Soullivaneuh relies on this label I think

**Comment by jordisala1991** [comment]
Remove this labels will require another PR following this one to remove some code from here: https://github.com/sonata-project/dev-kit/blob/master/src/GithubHookProcessor.php#L72

**Comment by Soullivaneuh** [comment]
> as github now provides a better workflow to handle PR's

Could you please elaborate @OskarStark?

As @jordisala1991 says, this label is used for automation and easy filtering, how could we replace it?

**Comment by Soullivaneuh** [comment]
> Maybe keep the RTM only for dashboard as @Soullivaneuh relies on this label I think

Same thing here. Do approvals really replace the fact the MR is ready to merge?

**Comment by OskarStark** [comment]
> Same thing here. Do approvals really replace the fact the MR is ready to merge?

Ok fine lets keep them, and filtering is great, but "review required" should then be removed if the PR is closed and merged, otherwise its useless, isn't it?

**Pull request closed without merging**
