### PR TITLE
Bump php version for dev kit

### PR DESCRIPTION
**Pull request by VincentLanglet**
I'm trying to run dev-kit on PHP 8.1 and Symfony 6.

Currently, 
- I bumped knplabs/github-api
- I bumped PHP version to 8.1
- I changed the git wrapper library since it doesn't support SF 6.

For SF 6, the current issue is
```
    - cache/redis-adapter 1.0.0 requires php ^5.6 || ^7.0 -> your php version (8.1; overridden via config.platform, actual: 8.2.3) does not satisfy that requirement.
    - symfony/cache[v6.2.0, ..., v6.2.7] require psr/cache ^2.0|^3.0 -> satisfiable by psr/cache[2.0.0, 3.0.0].
    - You can only install one version of a package, so only one of these can be installed: psr/cache[1.0.0, 1.0.1, 2.0.0, 3.0.0].
    - cache/redis-adapter 1.1.0 requires psr/cache ^1.0 -> satisfiable by psr/cache[1.0.0, 1.0.1].
    - Root composer.json requires cache/redis-adapter ^1.0 -> satisfiable by cache/redis-adapter[1.0.0, 1.1.0].
    - Root composer.json requires symfony/cache ^6.2 -> satisfiable by symfony/cache[v6.2.0, ..., v6.2.7].
```

Should we drop the cache/redis-adapter @jordisala1991 ?
It's used for the github client but I'm not sure it works well...

### CODE REVIEW

**Comment by jordisala1991** [comment]
Maybe we need another adapter, but redis is used to avoid hitting rate limiters on github side

**Comment by jordisala1991** [comment]
Why dont we use the official one? https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html

**Comment by VincentLanglet** [comment]
> Why dont we use the official one? [symfony.com/doc/current/components/cache/adapters/redis_adapter.html](https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html)

Indeed, nice idea

**Review by jordisala1991 — APPROVED** [review]

**Comment by VincentLanglet** [comment]
I broke the deploy :'( 
```
E: Error parsing configuration files:
      - applications: Uncaught exception: The "json" extension is not supported for php:8.1
          at <script>:118:12
                        throw("The \"" + unsupported_extensions[0] + "\" extension is not supported for " + service.type);
                        ^
  To git.eu-5.platform.sh:ptm4dx6rjpjko.git
   ! [remote rejected] HEAD -> master (invalid configuration files)
  error: failed to push some refs to 'git.eu-5.platform.sh:ptm4dx6rjpjko.git'
```

**Pull request merged**
