### PR TITLE
Drop php5

### PR DESCRIPTION
**Pull request by core23**
Based on the [twitter vote](https://twitter.com/core23de/status/817044245018185728), we could drop PHP5 completly for the next majors.

### CODE REVIEW

**Comment by greg0ire** [comment]
Might be a good occasion to add php `7.1`.

**Comment by core23** [comment]
@Soullivaneuh Your job :)

**Comment by Soullivaneuh** [comment]
Even I quite personally agree with that, PHP 5.6 still have security update.

In my very personal opinion, I would also like to remove the support of this kind of version.

But Sonata packages are also used by @rande company and it's a quite important change that make lot of debates on each open-source project.

I would like the "Go" of @rande before doing this.

**Comment by rande** [comment]
Hello, 

New majors are there to move forward, so I will be happy to drop php 5 on the next major.

**Comment by greg0ire** [comment]
Thanks @rande ! @Soullivaneuh , please merge and apply, this blocks #216

**Comment by Soullivaneuh** [comment]
Thank you @core23

**Pull request merged**
