### PR TITLE
Require ext-redis

### LINKED ISSUE #1354: Warning when running `bin/console release`
When I run `bin/console release` I get:
```
[WARNING] Some commands could not be registered:                                                                       
                                                                                                                        
In getClientService.php line 52:
  Class 'Redis' not found  
```

I think it's since https://github.com/sonata-project/dev-kit/pull/1133 @OskarStark 

Any way to fix this ?

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes #1354

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Please rebase

**Comment by VincentLanglet** [comment]
@OskarStark (@sonata-project/contributors) any idea why this is failing ?

**Review by phansys — APPROVED** [review]

**Comment by OskarStark** [comment]
Can you please rebase?

**Comment by VincentLanglet** [comment]
@OskarStark The dependencies are not installed on your phpstan github action.

```
Loading composer repositories with package information
  Installing dependencies from lock file
  Your requirements could not be resolved to an installable set of packages.
  
    Problem 1
      - The requested PHP extension ext-redis * is missing from your system. Install or enable PHP's redis extension.
```

**Comment by OskarStark** [comment]
Can you provide a PR on the github action?

**Comment by OskarStark** [comment]
This should work: https://github.com/OskarStark/phpstan-ga/pull/42

**Comment by OskarStark** [comment]
Can you try this change locally?

**Comment by VincentLanglet** [comment]
> Can you try this change locally?

How ?

**Comment by VincentLanglet** [comment]
I thought again, I think it's better to use
```
--ignore-platform-reqs
```
on the phpstan github action @OskarStark

**Comment by OskarStark** [comment]
Open for a PR to make it configurable?

**Comment by VincentLanglet** [comment]
> Open for a PR to make it configurable?

I discovered that the option already exists :)

**Pull request merged**
