### PR TITLE
Bump LTS version number

### PR DESCRIPTION
**Pull request by greg0ire**
https://github.com/sonata-project/SonataAdminBundle/pull/5843

### CODE REVIEW

**Comment by core23** [comment]
Only for the admin bundle?

**Comment by greg0ire** [comment]
Let's try for everyone I guess :P

**Comment by OskarStark** [comment]
Why not 4.3?

**Comment by greg0ire** [comment]
4.3 is not an LTS

**Comment by core23** [comment]
> 4.3 is not an LTS

... and general support ends this month

**Pull request merged**
