### PR TITLE
changed chmod

### PR DESCRIPTION
**Pull request by OskarStark**
as mentioned by @dbu this file should be executable, too

screenshot 2018-11-13 11 12 50

### CODE REVIEW

**Comment by greg0ire** [comment]
Hmmm wait… the twig file should not really be executable, only the produced sh file should. Are you sure this will work?

**Comment by OskarStark** [comment]
Hmm 🤔 you are right, but it is also the only twig file with 644...

Let’s see if it works

**Comment by dbu** [comment]
oh snap. okay, twig templates should not be executable. but there is another .twig file that already *is* executable, right? can we make the thing that compiles the .twig to an actual .sh do a chmod a+x on the generated files?

**Comment by greg0ire** [comment]
Looks like this is how it is supposed to work:

https://github.com/sonata-project/dev-kit/blob/4d1fe369fac7a3e3f60498373d79300da8e1c463/src/Console/Command/DispatchCommand.php#L534

**Comment by OskarStark** [comment]
> Shall we merge this then?

IIRC, it uses the CHMOD of the twig file, so YES

**Pull request merged**
