### PR TITLE
Use Symfony + SymfonyCloud

### PR DESCRIPTION
**Pull request by OskarStark**
> Can you explain a little bit, what this change is about? I never used symfony cloud.
>
> Do we need a new server / symfony cloud account?

I am currently try to get dev-kit running on SymfonyCloud.
I already talked to @soullivaneuh and @greg0ire. Afterwards @greg0ire and me can deploy the changes, we merged in dev-kit. Next step would be to deploy SymfonyCloud when we merge on master -> automatism!

Only @greg0ire and me should get access for now.

All you need to know you can ping one of us and we deploy the dev-kit changes. All cronjobs are running on this environment/server.

This server should then also receive the notifications from Github

### CODE REVIEW

**Comment by core23** [comment]
Can you explain a little bit, what this change is about? I never used symfony cloud.

Do we need a new server / symfony cloud account?

**Comment by OskarStark** [comment]
Sure thing, I updated the PR header

**Comment by core23** [comment]
- Is there a status page where we can see the current status of the dev-kit: e.g. last execution time?
- Is it possible to use the dev-kit for other projects (non-sonata)?

**Comment by OskarStark** [comment]
> Is there a status page where we can see the current status of the dev-kit: e.g. last execution time?

You mean which ist the deployed git sha?

Then endpoint is available here: https://d5zda2diva-x6miu6vkqhzpi.eu.s5y.io/

Currently I need to fix the REVISION generation

**Comment by core23** [comment]
> > Is there a status page where we can see the current status of the dev-kit: e.g. last execution time?
> 
> You mean which ist the deployed git sha?

Sort of. I mean something like https://fabbot.io/. Not that advanced, but the current revision is a good start.

**Comment by OskarStark** [comment]
Ah now, but we can ofc track that easily or list all PullRequest Urls ...

Btw. current REVISON is now available at: https://d5zda2diva-x6miu6vkqhzpi.eu.s5y.io/


But still some problem generating this automatically via GithubActions on `master`

**Pull request merged**
