### PR TITLE
Dispatch on github actions

### PR DESCRIPTION
**Pull request by jordisala1991**

### CODE REVIEW

**Comment by jordisala1991** [comment]
WDYT @sonata-project/contributors ?

The main idea about this PR is:
* We change files here often
* We have to remember to deploy each change to Symfony Cloud
* If we forget about it, changes don't get dispatched and we lose time
* Github actions offer cronjobs already, why don't we use that directly?

With this one we should be able to stop worrying about deploying each change to Symfony Cloud. I didn't migrate all crons because I thought it would be better starting with something, and if it works well then we can migrate the rest.

Symfony Cloud is still needed because we have a web interface with some nice tools. (But it could be handled via github actions too if we think about it. Not to be done here, but just food for thoughts).

**Comment by jordisala1991** [comment]
Of course it can be also improved later to:

* Not only have cronjob but a button to manually dispatch files
* Have a special comment on PRs to trigger a dispatch to show changes (without --apply)

**Comment by jordisala1991** [comment]
If we accept this change, the person who merges it should ensure to deploy one more time to Symfony Cloud to remove those crons.

**Review by VincentLanglet — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by VincentLanglet** [comment]
merged and deployed

**Pull request merged**
