### PR TITLE
Try shellcheck

### PR DESCRIPTION
**Pull request by soullivaneuh**
- [ ] Test on dev-kit
- [ ] Fix the shell scripts if necessary
- [ ] Find on fix shell scripts on sonata repositories if present

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Well, I have to modify the shellcheck service to only `*.sh` files.

**Comment by core23** [comment]
Ping @Soullivaneuh

**Comment by core23** [comment]
Are you still working on this or can we close this @soullivaneuh ?

**Comment by soullivaneuh** [comment]
To be honest, I will not be able to take time on it for now. Feel free to continue it if you want! :+1: 

But AFAIR, I have to add some fixes on the FlintCI shellcheck service before.

**Comment by OskarStark** [comment]
We didn’t need this in the past, so let’s close.
Feel free to reopen if ...

**Pull request closed without merging**
