### PR TITLE
Allow Travis CI to build on PHP 7.4

### PR DESCRIPTION
**Pull request by phansys**
## Subject

Allow Travis CI to build on PHP 7.4.

I am targeting this branch, because this change doesn't affect BC.

### CODE REVIEW

**Comment by greg0ire** [comment]
Proof PR: https://github.com/sonata-project/SonataAdminBundle/pull/5608

**Comment by soullivaneuh** [comment]
They are some conflict.

But what the point of adding an unstable version? We already have the nightly release.

**Comment by phansys** [comment]
>They are some conflict.
>
>But what the point of adding an unstable version? We already have the nightly release.

The goal is to test the codebase against a version that will be released in the next few months, which also will ship some nice features that we need today given the associations between our own bundles.
Moreover, `nightly` currently points against PHP 8.

What kind of conflicts you mean? Could I take a look?

**Comment by core23** [comment]
> What kind of conflicts you mean? Could I take a look?

I rebase your commits

**Comment by phansys** [comment]
Thank you @core23!

**Comment by soullivaneuh** [comment]
@phansys Just one question: Can't we just put `7.4`? In order to avoid a future CI brake because `7.4snapshot` will not be present.

**Comment by phansys** [comment]
I think that is not possible yet, at least not in a transparent way. I pushed a commit using `7.4` instead of `7.4snapshot`: https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/555785733.
See:
* https://twitter.com/nikita_ppv/status/1094897743594770433
* https://travis-ci.community/t/add-php-7-4-branch-to-test-against/2179.

**Comment by OskarStark** [comment]
We should merge this and when 7.4 is released rename it to „7.4“. It’s a breathe via dev-kit

**Comment by OskarStark** [comment]
and this one please @soullivaneuh ❤️

**Pull request merged**
