### PR TITLE
Remove travis files (part 1)

### PR DESCRIPTION
**Pull request by jordisala1991**
Output for classification-bundle:

```diff
diff --git a/.travis.yml b/.travis.yml
deleted file mode 100644
index bba8086..0000000
--- a/.travis.yml
+++ /dev/null
@@ -1,70 +0,0 @@
-# DO NOT EDIT THIS FILE!
-#
-# It's auto-generated by sonata-project/dev-kit package.
-
-branches:
-  only:
-    - master
-    - 3.x
-
-language: php
-
-php:
-  - '7.2'
-  - '7.3'
-  - '7.4'
-  - nightly
-
-services:
-  - mongodb
-
-dist: xenial
-
-cache:
-  directories:
-    - $HOME/.composer/cache/files
-
-env:
-  global:
-    - PATH="$HOME/.local/bin:$PATH"
-    - TARGET=test
-    - UPSTREAM_URL=https://github.com/sonata-project/SonataClassificationBundle.git
-
-matrix:
-  fast_finish: true
-  include:
-    - php: '7.2'
-      env: COMPOSER_FLAGS="--prefer-lowest"
-    - php: '7.3'
-      env: SYMFONY=4.4.*
-    - php: '7.3'
-      env: SYMFONY='dev-master as 4.4.x-dev'
-    - php: '7.3'
-      env: SONATA_ADMIN=3.*
-    - php: '7.3'
-      env: SONATA_ADMIN='dev-master as 3.x-dev'
-    - php: '7.3'
-      env: SYMFONY_DEPRECATIONS_HELPER=0
-  allow_failures:
-    - php: nightly
-    - env: SYMFONY_DEPRECATIONS_HELPER=0
-    - env: SYMFONY='dev-master as 4.4.x-dev'
-    - env: SONATA_ADMIN='dev-master as 3.x-dev'
-
-before_install:
-  - git remote add upstream ${UPSTREAM_URL} && git fetch --all
-  - if [[ -x .travis/check_relevant_${TARGET}.sh && "$TRAVIS_PULL_REQUEST" != "false" ]]; then export RELEVANT=$(.travis/check_relevant_${TARGET}.sh); fi;
-  - if [[ ! -z ${RELEVANT} ]];then exit 0; fi;
-  - if [ -x .travis/before_install_${TARGET}.sh ]; then .travis/before_install_${TARGET}.sh; fi;
-
-install:
-  - if [ -x .travis/install_${TARGET}.sh ]; then .travis/install_${TARGET}.sh; fi;
-
-before_script:
-  - phpenv config-rm xdebug.ini
-  - if [ -x .travis/before_script_${TARGET}.sh ]; then .travis/before_script_${TARGET}.sh; fi;
-
-script: make $TARGET
-
-after_success:
-  - if [ -x .travis/after_success_${TARGET}.sh ]; then .travis/after_success_${TARGET}.sh; fi;
diff --git a/.travis/after_success_test.sh b/.travis/after_success_test.sh
deleted file mode 100755
index ef9cea0..0000000
--- a/.travis/after_success_test.sh
+++ /dev/null
@@ -1,9 +0,0 @@
-#!/usr/bin/env sh
-
-# DO NOT EDIT THIS FILE!
-#
-# It's auto-generated by sonata-project/dev-kit package.
-
-set -ev
-
-coveralls -v
diff --git a/.travis/before_install_test.sh b/.travis/before_install_test.sh
deleted file mode 100755
index 970cfee..0000000
--- a/.travis/before_install_test.sh
+++ /dev/null
@@ -1,23 +0,0 @@
-#!/usr/bin/env bash
-
-# DO NOT EDIT THIS FILE!
-#
-# It's auto-generated by sonata-project/dev-kit package.
-
-set -ev
-
-PHP_INI_DIR="$HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/"
-TRAVIS_INI_FILE="$PHP_INI_DIR/travis.ini"
-echo "memory_limit=3072M" >> "$TRAVIS_INI_FILE"
-
-echo "extension=mongodb.so" >> "$TRAVIS_INI_FILE"
-
-# https://github.com/composer/composer/issues/5030
-composer config "platform.ext-mongo" "1.6.16"
-# Backwards compatibility with old mongo extension
-composer require "alcaeus/mongo-php-adapter"
-
-sed --in-place "s/\"dev-master\":/\"dev-${TRAVIS_COMMIT}\":/" composer.json
-
-if [ "$SYMFONY" != "" ]; then composer require "symfony/symfony:$SYMFONY" --no-update; fi;
-if [ "$SONATA_ADMIN" != "" ]; then composer require "sonata-project/admin-bundle:$SONATA_ADMIN" --no-update; fi;
diff --git a/.travis/before_script_test.sh b/.travis/before_script_test.sh
deleted file mode 100755
index 74788e5..0000000
--- a/.travis/before_script_test.sh
+++ /dev/null
@@ -1,12 +0,0 @@
-#!/usr/bin/env bash
-
-# DO NOT EDIT THIS FILE!
-#
-# It's auto-generated by sonata-project/dev-kit package.
-
-set -ev
-
-if [ -f .travis/before_script_test.local.sh ]
-then
-    ./.travis/before_script_test.local.sh
-fi
diff --git a/.travis/check_relevant_test.sh b/.travis/check_relevant_test.sh
deleted file mode 100755
index 6fa88cb..0000000
--- a/.travis/check_relevant_test.sh
+++ /dev/null
@@ -1,11 +0,0 @@
-#!/usr/bin/env bash
-
-# DO NOT EDIT THIS FILE!
-#
-# It's auto-generated by sonata-project/dev-kit package.
-
-set -ev
-
-RELEVANT_FILES=$(git diff --name-only HEAD upstream/${TRAVIS_BRANCH} -- '*.php' '*.yml' '*.xml' '*.twig' '*.js' '*.css' '*.json')
-
-if [[ -z ${RELEVANT_FILES} ]]; then echo -n 'KO'; exit 0; fi;
diff --git a/.travis/install_test.sh b/.travis/install_test.sh
deleted file mode 100755
index 70324c8..0000000
--- a/.travis/install_test.sh
+++ /dev/null
@@ -1,17 +0,0 @@
-#!/usr/bin/env sh
-
-# DO NOT EDIT THIS FILE!
-#
-# It's auto-generated by sonata-project/dev-kit package.
-
-set -ev
-
-mkdir --parents "${HOME}/bin"
-
-# Coveralls client install
-wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar --output-document="${HOME}/bin/coveralls"
-chmod u+x "${HOME}/bin/coveralls"
-
-pecl install pcov
-
-composer update --prefer-dist --no-interaction --prefer-stable ${COMPOSER_FLAGS}
diff --git a/README.md b/README.md
index ad0480f..cb8fd2c 100644
--- a/README.md
+++ b/README.md
@@ -16,10 +16,10 @@ Symfony SonataClassificationBundle
 [![Monthly Downloads](https://poser.pugx.org/sonata-project/classification-bundle/d/monthly)](https://packagist.org/packages/sonata-project/classification-bundle)
 [![Daily Downloads](https://poser.pugx.org/sonata-project/classification-bundle/d/daily)](https://packagist.org/packages/sonata-project/classification-bundle)

-Branch | Travis | Coveralls |
------- | ------ | --------- |
-3.x   | [![Build Status][travis_stable_badge]][travis_stable_link]     | [![Coverage Status][coveralls_stable_badge]][coveralls_stable_link]     |
-master | [![Build Status][travis_unstable_badge]][travis_unstable_link] | [![Coverage Status][coveralls_unstable_badge]][coveralls_unstable_link] |
+Branch | Github Actions | Coverage |
+------ | -------------- | -------- |
+3.x    | [![Test][test_stable_badge]][test_stable_link]     | [![Coverage Status][coverage_stable_badge]][coverage_stable_link]     |
+master | [![Test][test_unstable_badge]][test_unstable_link] | [![Coverage Status][coverage_unstable_badge]][coverage_unstable_link] |

 ## Documentation

@@ -36,12 +36,12 @@ If you think you found a bug or you have a feature idea to propose, feel free to

 This package is available under the [MIT license](LICENSE).

-[travis_stable_badge]: https://travis-ci.org/sonata-project/SonataClassificationBundle.svg?branch=3.x
-[travis_stable_link]: https://travis-ci.org/sonata-project/SonataClassificationBundle
-[travis_unstable_badge]: https://travis-ci.org/sonata-project/SonataClassificationBundle.svg?branch=master
-[travis_unstable_link]: https://travis-ci.org/sonata-project/SonataClassificationBundle
+[test_stable_badge]: https://github.com/sonata-project/SonataClassificationBundle/workflows/Test/badge.svg?branch=3.x
+[test_stable_link]: https://github.com/sonata-project/SonataClassificationBundle/actions?query=workflow:test+branch:3.x
+[test_unstable_badge]: https://github.com/sonata-project/SonataClassificationBundle/workflows/Test/badge.svg?branch=master
+[test_unstable_link]: https://github.com/sonata-project/SonataClassificationBundle/actions?query=workflow:test+branch:master

-[coveralls_stable_badge]: https://coveralls.io/repos/github/sonata-project/SonataClassificationBundle/badge.svg?branch=3.x
-[coveralls_stable_link]: https://coveralls.io/github/sonata-project/SonataClassificationBundle?branch=3.x
-[coveralls_unstable_badge]: https://coveralls.io/repos/github/sonata-project/SonataClassificationBundle/badge.svg?branch=master
-[coveralls_unstable_link]: https://coveralls.io/github/sonata-project/SonataClassificationBundle?branch=master
+[coverage_stable_badge]: https://codecov.io/gh/sonata-project/SonataClassificationBundle/branch/3.x/graph/badge.svg
+[coverage_stable_link]: https://codecov.io/gh/sonata-project/SonataClassificationBundle/branch/3.x
+[coverage_unstable_badge]: https://codecov.io/gh/sonata-project/SonataClassificationBundle/branch/master/graph/badge.svg
+[coverage_unstable_link]: https://codecov.io/gh/sonata-project/SonataClassificationBundle/branch/master
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Proof PR: https://github.com/sonata-project/SonataClassificationBundle/pull/565

**Comment by jordisala1991** [comment]
@OskarStark some required checks does not seem correct

**Comment by OskarStark** [comment]
Please remove the badges from the README

**Comment by OskarStark** [comment]
And add this `https://notify.travis-ci.org` to the const for the hooks to be deleted in `DispatchCommand`

**Comment by core23** [comment]
>     * [ ]  Please remove the badges from the README

... and ...

[ ] Add new GitHub Pipeline badges

**Comment by jordisala1991** [comment]
Done

**Review by VincentLanglet — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Review by greg0ire — APPROVED** [review]

**Pull request merged**
